#!/usr/bin/env python3
"""Generate the authoritative Bedrock packet-id table from minecraft-data.

Why a generator: the packet ids and field orders are protocol facts, not
guesses. An earlier hand-written table drifted (it claimed MobEffect 0x1a and
PlayerAction 0x0d; upstream says 0x1c and 0x24), and a module that filters the
wrong id silently does nothing. This reads upstream's `proto.yml` and emits:

  app/src/main/java/dev/xykell/client/runtime/relay/BedrockPacketIds.kt
  registry/bedrock-packets.json          (reference: id, bound, name)

Source data: PrismarineJS/minecraft-data `data/bedrock/<version>/proto.yml`
(MIT). Sanity check in --check mode: the four packets the relay already
decodes by hand (Text 0x09, SetTime 0x0a, MovePlayer 0x13, SetHealth 0x2a)
must match, or the upstream version is wrong and we refuse to emit.

Usage:
  python3 scripts/protocol/gen_packet_ids.py --proto <path/to/proto.yml>
  python3 scripts/protocol/gen_packet_ids.py --proto <path> --check
"""
import argparse
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]

# The relay's hand-written decoder in BedrockPackets.kt is already trusted and
# cross-checked against upstream. If upstream ever disagrees, the version we
# vendored is not the one the relay speaks, and emitting would be worse than
# failing.
KNOWN = {"Text": 0x09, "SetTime": 0x0A, "MovePlayer": 0x13, "SetHealth": 0x2A}

PACKET_RE = re.compile(r"^(packet_[a-z0-9_]+):\s*$")
ID_RE = re.compile(r"^\s*!id:\s*(\S+)")
BOUND_RE = re.compile(r"^\s*!bound:\s*(\S+)")
FIELD_RE = re.compile(r"^\s*([a-zA-Z_][a-zA-Z0-9_]*):\s*(.+?)\s*$")
NEXT_TYPE_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*:")


def camel(name):
    return "".join(p[:1].upper() + p[1:] for p in name[len("packet_"):].split("_"))


def parse(proto_text):
    """-> {CamelName: {id, bound, fields}} for every packet with an !id."""
    packets = {}
    order = []
    cur = None
    for line in proto_text.splitlines():
        m = PACKET_RE.match(line)
        if m:
            cur = m.group(1)
            packets.setdefault(cur, {"fields": []})
            order.append(cur)
            continue
        if cur is None:
            continue
        m = ID_RE.match(line)
        if m:
            packets[cur]["id"] = m.group(1)
            continue
        m = BOUND_RE.match(line)
        if m:
            packets[cur]["bound"] = m.group(1)
            continue
        m = FIELD_RE.match(line)
        # A field is indented; a new top-level type definition is at column 0.
        if m and line[:1] in (" ", "\t") and not line.lstrip().startswith("!"):
            packets[cur]["fields"].append([m.group(1), m.group(2)])
            continue
        if line.strip() and not line.startswith((" ", "\t", "#")):
            cur = None
    return {k: v for k, v in packets.items() if "id" in v}


def resolve(packets):
    out = {}
    for key, spec in packets.items():
        name = camel(key)
        bound = spec.get("bound", "both")
        out[name] = {
            "name": name,
            "packet": key,
            "id": int(spec["id"], 0),
            "hex": spec["id"],
            "bound": bound,
            # client = server->client, server = client->server, both = either
            "toClient": bound in ("client", "both"),
            "toServer": bound in ("server", "both"),
            "fields": spec["fields"],
        }
    return out


def emit_kotlin(table):
    lines = [
        "package dev.xykell.client.runtime.relay",
        "",
        "/**",
        " * Bedrock packet ids, generated by scripts/protocol/gen_packet_ids.py from",
        " * upstream minecraft-data `proto.yml` (MIT). Do not hand-edit: an earlier",
        " * hand-written table drifted (it claimed MobEffect 0x1a and PlayerAction",
        " * 0x0d; upstream says 0x1c and 0x24) and a module filtering the wrong id",
        " * silently does nothing at all.",
        " *",
        " * `toClient`/`toServer` are the authoritative direction flags. A packet",
        " * with toClient=false never travels toward the game, so a transform that",
        " * only makes sense on one leg can be scoped to it.",
        " */",
        "object BedrockPacketIds {",
        "",
        "    data class Info(val id: Int, val toClient: Boolean, val toServer: Boolean)",
        "",
        "    private val TABLE: Map<String, Info> = mapOf(",
    ]
    for name in sorted(table):
        e = table[name]
        lines.append(
            '        "%s" to Info(0x%02x, toClient = %s, toServer = %s),'
            % (name, e["id"], str(e["toClient"]).lower(), str(e["toServer"]).lower())
        )
    lines += [
        "    )",
        "",
        "    private val BY_ID: Map<Int, String> = TABLE.entries",
        "        .associate { (name, info) -> info.id to name }",
        "",
        "    /** Packet id -> name, or null when the id is unknown. */",
        "    fun nameOf(id: Int): String? = BY_ID[id]",
        "",
        "    /** Direction flags for [id], or null when the id is unknown. */",
        "    fun infoOf(id: Int): Info? = BY_ID[id]?.let { TABLE.getValue(it) }",
        "",
        "    fun infoOf(name: String): Info? = TABLE[name]",
        "",
        "    val allNames: Set<String> get() = TABLE.keys",
        "}",
        "",
    ]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--proto", required=True, help="path to upstream bedrock proto.yml")
    ap.add_argument("--check", action="store_true", help="verify only, write nothing")
    args = ap.parse_args()

    table = resolve(parse(pathlib.Path(args.proto).read_text()))
    print("parsed %d packets" % len(table), file=sys.stderr)

    for name, want in KNOWN.items():
        got = table.get(name, {}).get("id")
        if got != want:
            print(
                "MISMATCH %s: upstream=%s expected=0x%02x — wrong upstream version"
                % (name, got, want),
                file=sys.stderr,
            )
            return 1
    print("cross-check against the hand-written decoder: PASS", file=sys.stderr)

    if args.check:
        return 0

    kt = ROOT / "app/src/main/java/dev/xykell/client/runtime/relay/BedrockPacketIds.kt"
    kt.write_text(emit_kotlin(table))
    print("wrote %s" % kt, file=sys.stderr)

    ref = ROOT / "registry/bedrock-packets.json"
    ref.write_text(json.dumps(table, indent=1, sort_keys=True) + "\n")
    print("wrote %s" % ref, file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())