package dev.xykell.client.runtime.observation

import org.json.JSONObject
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Test

/**
 * Host JVM tests for the Phase-1 observation pipeline (Stage 20).
 * Deterministic fixtures + hardcoded cross-implementation vectors
 * (generated by the Node lab; see STAGE-20 doc). Run on CI;
 * on-device JVM execution is unavailable (no kotlinc/Gradle/SDK).
 */
class ObservationPipelineTest {

    // --- endpoint enforcement: exact constant accepted, everything else refused ---

    @Test
    fun endpoint_exactConstantAccepted() {
        LoopbackWebSocket.buildRequest("ws://127.0.0.1:8765")
    }

    @Test
    fun endpoint_rejections() {
        val bad = listOf(
            "ws://localhost:8765",
            "ws://[::1]:8765",
            "ws://127.0.0.2:8765",
            "ws://192.168.1.10:8765",
            "ws://example.com:8765",
            "ws://127.0.0.1:8766",
            "wss://127.0.0.1:8765",
            "http://127.0.0.1:8765",
            "",
            "ws://127.0.0.1:8765/extra",
        )
        for (url in bad) {
            try {
                LoopbackWebSocket.buildRequest(url)
                fail("accepted forbidden endpoint: $url")
            } catch (e: IllegalArgumentException) {
                // expected: fail immediately
            }
        }
        assertEquals("ws://127.0.0.1:8765", LoopbackWebSocket.ENDPOINT)
    }

    // --- state machine: IDLE/STARTING/OBSERVING/STOPPED/FAILED, no auto-reconnect ---

    @Test
    fun fsm_lifecycle() {
        val fsm = ObservationStateMachine()
        assertEquals(ObservationState.IDLE, fsm.state)
        assertTrue(fsm.start())
        assertEquals(ObservationState.STARTING, fsm.state)
        fsm.onEstablished()
        assertEquals(ObservationState.OBSERVING, fsm.state)
        fsm.stop()
        assertEquals(ObservationState.STOPPED, fsm.state)
    }

    @Test
    fun fsm_failureAndFreshRestart() {
        val fsm = ObservationStateMachine()
        fsm.start()
        fsm.fail("endpoint-rejected")
        assertEquals(ObservationState.FAILED, fsm.state)
        assertEquals("endpoint-rejected", fsm.detail)
        assertTrue(fsm.start()) // explicit restart creates fresh state
        assertEquals(ObservationState.STARTING, fsm.state)
        assertEquals("", fsm.detail)
    }

    @Test
    fun fsm_closeIsTerminal() {
        val fsm = ObservationStateMachine()
        fsm.start()
        fsm.onEstablished()
        fsm.onClosed()
        assertEquals(ObservationState.STOPPED, fsm.state)
        // No auto-reconnect: redundant start only from resting states.
        val running = ObservationStateMachine()
        running.start()
        assertEquals(false, running.start())
    }

    // --- buffer: cap 64, drop-oldest, monotonic overflow, bounded ---

    @Test
    fun buffer_capacityAndOverflow() {
        val p = LiveProducer()
        repeat(64) { i ->
            p.offer(ChatMessage("id-$i", i.toLong(), "s", "m$i"))
        }
        assertEquals(64, p.size())
        assertEquals(0L, p.overflowCount)
        p.offer(ChatMessage("id-64", 64L, "s", "m64")) // 65th drops oldest
        assertEquals(64, p.size())
        assertEquals(1L, p.overflowCount)
        val first = p.pollNext()
        assertEquals(LiveProducer.Poll.ITEM, first.poll)
        assertEquals("m1", (first.item as ChatMessage).message)
        // Drain fully, then EMPTY forever (bounded, deterministic).
        repeat(63) { p.pollNext() }
        assertEquals(LiveProducer.Poll.EMPTY, p.pollNext().poll)
        assertEquals(1L, p.overflowCount) // counter monotonic, never reset by drain
    }

    // --- translation: exact Stage-10 fields, unknown/invalid split ---

    @Test
    fun translate_chatExact() {
        val env = JSONObject(
            """{"header":{"eventName":"PlayerMessage","messagePurpose":"event"},
                "body":{"message":"  Hi!  ","receiver":"","sender":"S","type":"chat"}}""",
        )
        val r = ObservationTranslator.translate(env, "e1", 7L, 160)
        assertTrue(r is ChatMessage)
        r as ChatMessage
        assertEquals("  Hi!  ", r.message) // byte-exact, no normalization
        assertEquals("S", r.sender)
        assertEquals(7L, r.observedAtMs)
    }

    @Test
    fun translate_travelExact() {
        val env = JSONObject(
            """{"header":{"eventName":"PlayerTravelled","messagePurpose":"event"},
                "body":{"metersTravelled":1.054,"travelMethod":2,
                "player":{"position":{"x":-1.5,"y":64.0,"z":3.25},"yRot":-7.31}}}""",
        )
        val r = ObservationTranslator.translate(env, "e2", 8L, 405)
        assertTrue(r is Travelled)
        r as Travelled
        assertEquals(-1.5, r.x, 0.0)
        assertEquals(64.0, r.y, 0.0)
        assertEquals(3.25, r.z, 0.0)
        assertEquals(-7.31, r.yawDegrees, 0.0)
        assertEquals(1.054, r.metersTravelled, 0.0)
        assertEquals(2, r.travelMethod) // raw, unmapped
    }

    @Test
    fun translate_unknownVsInvalid() {
        val unknownEvent = JSONObject(
            """{"header":{"eventName":"Nope","messagePurpose":"event"},"body":{}}""",
        )
        val u = ObservationTranslator.translate(unknownEvent, "e3", 9L, 404)
        assertTrue(u is UnknownFrame)
        assertEquals("unrecognized-event", (u as UnknownFrame).reason)
        assertNull(ObservationTranslator.translate(JSONObject("""{"a":1}"""), "e4", 9L, 0))
        assertNull(ObservationTranslator.translate(null, "e5", 9L, 0))
        val badMeters = JSONObject(
            """{"header":{"eventName":"PlayerTravelled","messagePurpose":"event"},
                "body":{"metersTravelled":"far","travelMethod":0,
                "player":{"position":{"x":0,"y":0,"z":0},"yRot":0}}}""",
        )
        assertNull(ObservationTranslator.translate(badMeters, "e6", 9L, 0))
    }

    // --- crypto parity: hardcoded Node-generated vectors (Stage-20 doc) ---

    @Test
    fun crypto_base64Alphabet() {
        assertEquals("+//+", ObservationCrypto.b64u(byteArrayOf(0xFB.toByte(), 0xFF.toByte(), 0xFE.toByte())))
        assertEquals("AAECAw", ObservationCrypto.b64u(byteArrayOf(0, 1, 2, 3)))
        assertEquals("EA", ObservationCrypto.b64u(byteArrayOf(16)))
        assertEquals("//79/Ps", ObservationCrypto.b64u(byteArrayOf(0xFF.toByte(), 0xFE.toByte(), 0xFD.toByte(), 0xFC.toByte(), 0xFB.toByte())))
    }

    @Test
    fun crypto_spkiLength() {
        val pair = ObservationCrypto.generateEphemeralKeyPair()
        assertEquals(120, ObservationCrypto.spkiDer(pair).size)
        assertEquals(16, ObservationCrypto.randomSalt().size)
    }

    @Test
    fun crypto_ecdhPeerImportAndSecretShape() {
        // Fixed peer: Node createECDH(secp384r1), priv 0x22*48; SPKI DER.
        val peerSpki = hex(
            "3076301006072a8648ce3d020106052b81040022" +
                "03620004386e767ea5cb716c9cd620ff7342129c892a6fccefe612140c80" +
                "bff59e943468019dda16e5079b0c1d9001d23a624b6dd088d0c38263941" +
                "94787403e8a7d07e5e22f7e9c0b8e80fa1faff5d28b4bb597b267f0b8702" +
                "3ca61fc8454bddefd2e0e",
        )
        assertEquals(120, peerSpki.size)
        val peer = ObservationCrypto.importPeerSpki(peerSpki)
        val local = ObservationCrypto.generateEphemeralKeyPair()
        val secret = ObservationCrypto.agreeX384(local.private, peer)
        assertEquals(48, secret.size) // x-coordinate, padded to P-384 size
        val key = ObservationCrypto.deriveKey(ByteArray(16) { it.toByte() }, secret)
        assertEquals(32, key.size)
    }

    @Test
    fun crypto_kdfParity() {
        // Node: SHA-256(salt 0011..ff + fixed 48 B secret) — deterministic.
        val salt = hex("00112233445566778899aabbccddeeff")
        val secret = hex(
            "2ac3da23c114b5b1f3aa200cf3c57bebd1b3b880a0e68066ab5d00dda50dc" +
                "fe6cd03410292346187a84b1f12d53569c0",
        )
        assertArrayEquals(
            hex("726f9b54ca68fd49049c249b26dd54de0da7dfe61f44ac758eb597c27488c370"),
            ObservationCrypto.deriveKey(salt, secret),
        )
    }

    @Test
    fun crypto_cfb8VectorAndRoundtrip() {
        // Node aes-256-cfb8 fixed key/iv/plaintext vector.
        val key = hex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f")
        val iv = hex("000102030405060708090a0b0c0d0e0f")
        val pt = """{"header":{"eventName":"PlayerMessage"},"body":{"message":"hi"}}"""
            .toByteArray(Charsets.UTF_8)
        val expectedCt = hex(
            "21df97d7cd4570f23f79c11668ac5efe62e821784fa9e3dfa69a8cbfd03ae51" +
                "29fd3a862d0d9b2aea4fc26bcece034e293cf7add7f305f461f397a2e89a6f96f",
        )
        val enc = ObservationCrypto.Cfb8Stream(key, decrypt = false)
        assertArrayEquals(expectedCt, enc.update(pt))
        val dec = ObservationCrypto.Cfb8Stream(key, decrypt = true)
        assertArrayEquals(pt, dec.update(expectedCt))
        // Streaming continues across chunks (persistent stream semantics).
        val s1 = ObservationCrypto.Cfb8Stream(key, decrypt = false)
        val s2 = ObservationCrypto.Cfb8Stream(key, decrypt = true)
        val c1 = s1.update("hello ".toByteArray())
        val c2 = s1.update("world".toByteArray())
        assertEquals("hello world", String(s2.update(c1) + s2.update(c2), Charsets.UTF_8))
    }

    // --- security: endpoint constant + hardcoded localhost posture ---

    @Test
    fun security_noRemoteSurface() {
        assertEquals("ws://127.0.0.1:8765", LoopbackWebSocket.ENDPOINT)
        assertEquals("com.microsoft.minecraft.wsencrypt", LoopbackWebSocket.SUBPROTOCOL)
        assertEquals(listOf("PlayerMessage", "PlayerTravelled"), LoopbackWebSocket.SUBSCRIBED_EVENTS)
    }

    @Test
    fun observationExternal_attachOffersDetachDrops() {
        val seen = mutableListOf<Translated>()
        try {
            // No sink: offer reports drop, never throws.
            assertEquals(false, ObservationExternal.offer(
                ChatMessage("relay-x", 1L, "a", "b"),
            ))
            ObservationExternal.attach { seen.add(it) }
            assertEquals(true, ObservationExternal.offer(
                ChatMessage("relay-1", 1L, "a", "b"),
            ))
            assertEquals(1, seen.size)
            ObservationExternal.detach()
            assertEquals(false, ObservationExternal.offer(
                ChatMessage("relay-2", 2L, "c", "d"),
            ))
            assertEquals(1, seen.size)
        } finally {
            ObservationExternal.detach()
        }
    }

    private fun hex(s: String): ByteArray {
        require(s.length % 2 == 0)
        return ByteArray(s.length / 2) { i ->
            s.substring(i * 2, i * 2 + 2).toInt(16).toByte()
        }
    }
}
