#!/usr/bin/env bash
# Full-source Kotlin typecheck for app/ on the phone (no Gradle/aapt2 on ARM64).
# kotlinc compiles ALL main Kotlin sources against android.jar + androidx +
# a generated R stub (aapt2 is x86-64 only — see docs/M1.5-RESULTS.md).
# Complements run-kotlin-unit.sh (which runs the 6 pure-JVM suites): this one
# catches compile errors in the Android glue BEFORE CI sees them.
# Toolchain (all SHA-verified, all OUTSIDE the repo):
#   ~/local/opt/kotlinc                 kotlinc 1.9.24 (.sha256 checked)
#   ~/local/opt/jvm-jars/*.jar          okhttp 4.12.0, okio-jvm 3.6.0 (SHA-1)
#   ~/local/opt/androidx-jars/*.jar     appcompat/fragment/core/activity/... (SHA-1)
#   $ANDROID_SDK/platforms/*/android.jar
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

KOTLINC_BIN="${KOTLINC:-$HOME/local/opt/kotlinc/bin/kotlinc}"
JARS_DIR="${XYKELL_JVM_JARS:-$HOME/local/opt/jvm-jars}"
AX_DIR="${XYKELL_ANDROIDX_JARS:-$HOME/local/opt/androidx-jars}"
ANDROID_JAR="${XYKELL_ANDROID_JAR:-$HOME/android-sdk/platforms/android-35/android.jar}"
WORK="${XYKELL_TYPECHECK_WORK:-/data/data/com.termux/files/usr/tmp/opencode/xykell-typecheck}"

fail() { echo "KOTLIN-TYPECHECK: FAIL — $*" >&2; exit 1; }

[ -x "$KOTLINC_BIN" ] || fail "kotlinc not found at $KOTLINC_BIN"
for jar in okhttp-4.12.0.jar okio-jvm-3.6.0.jar; do
    [ -f "$JARS_DIR/$jar" ] || fail "missing $JARS_DIR/$jar"
done
[ -f "$ANDROID_JAR" ] || fail "missing $ANDROID_JAR (set XYKELL_ANDROID_JAR)"
shopt -s nullglob
AX_JARS=("$AX_DIR"/*.jar)
[ ${#AX_JARS[@]} -gt 0 ] || fail "no jars in $AX_DIR (run resolve step, see docs/TESTING.md)"

rm -rf "$WORK" && mkdir -p "$WORK/classes"

# --- R stub: generated from res/ (aapt2 unavailable on device) -------------
# Only symbols referenced from Kotlin land here: color/id/layout/string/style.
R_STUB="$WORK/R.kt"
python3 - "$ROOT/app/src/main/res" "$R_STUB" <<'PYEOF'
import re, sys, pathlib
res, out = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
pkg = "dev.xykell.client"
names = {"id": set(), "layout": set(), "string": set(), "color": set(), "style": set(), "drawable": set()}
for xml in res.rglob("*.xml"):
    text = xml.read_text(encoding="utf-8")
    names["id"].update(re.findall(r"@\+id/(\w+)", text))
    if xml.parent.name == "layout":
        names["layout"].add(xml.stem)
    for kind in ("string", "color", "style", "drawable"):
        names[kind].update(re.findall(r'<%s name="([\w.]+)"' % kind, text))
# @style refs in layouts may point at themes not yet in values
for xml in res.rglob("*.xml"):
    names["style"].update(re.findall(r"[@?]style/(\w+)", xml.read_text(encoding="utf-8")))
# drawable references in layouts
for xml in res.rglob("*.xml"):
    text = xml.read_text(encoding="utf-8")
    names["drawable"].update(re.findall(r"@drawable/(\w+)", text))
    names["drawable"].update(re.findall(r"@drawable:(\w+)", text))
# drawable references in Kotlin source (R.drawable.xxx)
for kt in pathlib.Path(sys.argv[1]).parent.rglob("*.kt"):
    text = kt.read_text(encoding="utf-8")
    names["drawable"].update(re.findall(r"R\.drawable\.(\w+)", text))
lines = ["// Generated by run-kotlin-typecheck.sh — DO NOT EDIT (res/ is the source)",
         "package %s" % pkg, "", "object R {"]
for kind in sorted(names):
    if not names[kind]:
        continue
    lines.append("    object %s {" % kind)
    for n in sorted(names[kind]):
        lines.append("        const val %s: Int = 0" % n.replace(".", "_"))
    lines.append("    }")
lines.append("}")
out.write_text("\n".join(lines) + "\n", encoding="utf-8")
total = sum(len(v) for v in names.values())
print("R stub: %d symbols (%s)" % (total, ", ".join("%s=%d" % (k, len(v)) for k, v in sorted(names.items()))))
PYEOF

# --- compile every main Kotlin source --------------------------------------
CP="$ANDROID_JAR"
CP="$CP:$JARS_DIR/okhttp-4.12.0.jar:$JARS_DIR/okio-jvm-3.6.0.jar"
for j in "${AX_JARS[@]}"; do CP="$CP:$j"; done
KOTLINC_HOME="$(cd "$(dirname "$KOTLINC_BIN")/.." && pwd)"
CP="$CP:$KOTLINC_HOME/lib/kotlin-stdlib.jar:$KOTLINC_HOME/lib/kotlin-stdlib-jdk8.jar:$KOTLINC_HOME/lib/kotlin-stdlib-jdk7.jar"

mapfile -t SOURCES < <(find "$ROOT/app/src/main/java" -name '*.kt' | sort)
[ ${#SOURCES[@]} -gt 0 ] || fail "no Kotlin sources found under app/src/main/java"

if ! "$KOTLINC_BIN" -J-Xmx1400m -nowarn -cp "$CP" -d "$WORK/classes" \
        "${SOURCES[@]}" "$R_STUB" 2> "$WORK/kotlinc.log"; then
    echo "KOTLIN-TYPECHECK: FAIL — kotlinc compile error (${#SOURCES[@]} sources)" >&2
    # Errors only: dump the real diagnostics, not warnings.
    grep -E "error:" "$WORK/kotlinc.log" | head -50 >&2 || cat "$WORK/kotlinc.log" >&2
    exit 1
fi

echo "KOTLIN-TYPECHECK: PASS (${#SOURCES[@]} sources compiled)"

# --- compile the test sourceset too ----------------------------------------
# Gradle builds app/src/test as its own compilation, so a test file importing a
# dependency the app never declared fails the build and nothing else. That is
# how AccountStoreTest sat broken for several CI runs: it imported
# androidx.test.core.app.ApplicationProvider with no such dependency. Compiling
# the test sources here catches the whole class on the phone.
TEST_CP="$CP:$WORK/classes:$JARS_DIR/junit-4.13.2.jar:$JARS_DIR/hamcrest-core-1.3.jar"
if [ -f "$JARS_DIR/junit-4.13.2.jar" ]; then
    mapfile -t TEST_SOURCES < <(find "$ROOT/app/src/test/java" -name '*.kt' | sort)
    if [ ${#TEST_SOURCES[@]} -gt 0 ]; then
        # -Xfriend-paths mirrors Gradle's associated test compilation, which is
        # what makes `internal` members visible to app/src/test.
        if "$KOTLINC_BIN" -J-Xmx1400m -nowarn -cp "$TEST_CP" -Xfriend-paths="$WORK/classes" \
                -d "$WORK/test-classes" "${TEST_SOURCES[@]}" \
                2> "$WORK/kotlinc-test.log"; then
            echo "KOTLIN-TYPECHECK: PASS (${#TEST_SOURCES[@]} test sources compiled)"
        else
            echo "KOTLIN-TYPECHECK: FAIL — test source compile error (${#TEST_SOURCES[@]} sources)" >&2
            grep -E "error:" "$WORK/kotlinc-test.log" | head -50 >&2 || cat "$WORK/kotlinc-test.log" >&2
            exit 1
        fi
    fi
else
    echo "KOTLIN-TYPECHECK: skip test sources (no junit jar)" >&2
fi
rm -rf "$WORK"
